apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: iasg68gvk-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe-java-quarkus:96d0f55a49e126d07f5763c1211b2578e67987ec@sha256:bee9716a01140b5fe426b076bb6d675a27ee1d693666ba830e1df784b77af031
          name: container-image
